
BLOCKSDS	?= /opt/blocksds/core

SOURCEDIRS	= arm9/source common/helix
INCLUDEDIRS	= common common/helix
GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9

# MP3 does not compile with "-mthumb" argument. Use -mthumb-interwork instead
ARCH		= -mthumb-interwork -mcpu=arm946e-s+nofp