// Autogenerated file

#ifndef ATLAS_H__
#define ATLAS_H__

#include <stdint.h>

#define ATLAS_BITMAP_WIDTH   256
#define ATLAS_BITMAP_HEIGHT  512
#define ATLAS_NUM_IMAGES     78

#define ATLAS_01_png 0
#define ATLAS_02_png 1
#define ATLAS_03_png 2
#define ATLAS_04_png 3
#define ATLAS_05_png 4
#define ATLAS_06_png 5
#define ATLAS_07_png 6
#define ATLAS_08_png 7
#define ATLAS_09_png 8
#define ATLAS_10_png 9
#define ATLAS_11_png 10
#define ATLAS_12_png 11
#define ATLAS_13_png 12
#define ATLAS_14_png 13
#define ATLAS_15_png 14
#define ATLAS_16_png 15
#define ATLAS_17_png 16
#define ATLAS_18_png 17
#define ATLAS_19_png 18
#define ATLAS_20_png 19
#define ATLAS_21_png 20
#define ATLAS_22_png 21
#define ATLAS_23_png 22
#define ATLAS_24_png 23
#define ATLAS_25_png 24
#define ATLAS_26_png 25
#define ATLAS_27_png 26
#define ATLAS_28_png 27
#define ATLAS_29_png 28
#define ATLAS_30_png 29
#define ATLAS_31_png 30
#define ATLAS_32_png 31
#define ATLAS_33_png 32
#define ATLAS_34_png 33
#define ATLAS_35_png 34
#define ATLAS_36_png 35
#define ATLAS_37_png 36
#define ATLAS_38_png 37
#define ATLAS_39_png 38
#define ATLAS_40_png 39
#define ATLAS_41_png 40
#define ATLAS_42_png 41
#define ATLAS_43_png 42
#define ATLAS_44_png 43
#define ATLAS_45_png 44
#define ATLAS_46_png 45
#define ATLAS_47_png 46
#define ATLAS_48_png 47
#define ATLAS_49_png 48
#define ATLAS_50_png 49
#define ATLAS_51_png 50
#define ATLAS_52_png 51
#define ATLAS_53_png 52
#define ATLAS_54_png 53
#define ATLAS_55_png 54
#define ATLAS_56_png 55
#define ATLAS_57_png 56
#define ATLAS_58_png 57
#define ATLAS_59_png 58
#define ATLAS_60_png 59
#define ATLAS_61_png 60
#define ATLAS_62_png 61
#define ATLAS_63_png 62
#define ATLAS_64_png 63
#define ATLAS_65_png 64
#define ATLAS_66_png 65
#define ATLAS_67_png 66
#define ATLAS_68_png 67
#define ATLAS_69_png 68
#define ATLAS_70_png 69
#define ATLAS_71_png 70
#define ATLAS_72_png 71
#define ATLAS_73_png 72
#define ATLAS_74_png 73
#define ATLAS_75_png 74
#define ATLAS_76_png 75
#define ATLAS_77_png 76
#define ATLAS_78_png 77

extern const uint16_t ATLAS_texcoords[];

#endif // ATLAS_H__
