// Autogenerated file

#ifndef TSC_H__
#define TSC_H__

#include <stdint.h>

#define TSC_BITMAP_WIDTH   128
#define TSC_BITMAP_HEIGHT  128
#define TSC_NUM_IMAGES     8

#define TSC_01_png 0
#define TSC_02_png 1
#define TSC_03_png 2
#define TSC_04_png 3
#define TSC_05_png 4
#define TSC_06_png 5
#define TSC_07_png 6
#define TSC_08_png 7

extern const uint16_t TSC_texcoords[];

#endif // TSC_H__
