// Autogenerated file

#include <stdint.h>

const uint16_t TSC_texcoords[] = {
    96, 0, 32, 28, // 01.png
    0, 102, 34, 23, // 02.png
    0, 0, 50, 26, // 03.png
    0, 61, 35, 41, // 04.png
    35, 61, 44, 38, // 05.png
    0, 26, 46, 35, // 06.png
    79, 45, 36, 35, // 07.png
    50, 0, 46, 45, // 08.png
};