// Autogenerated file

#include <stdint.h>

const uint16_t CSSMUGS_texcoords[] = {
    32, 96, 32, 32, // 01.png
    32, 64, 32, 32, // 02.png
    96, 32, 32, 32, // 03.png
    64, 32, 32, 32, // 04.png
    32, 32, 32, 32, // 05.png
    0, 96, 32, 32, // 06.png
    0, 64, 32, 32, // 07.png
    0, 32, 32, 32, // 08.png
    96, 0, 32, 32, // 09.png
    64, 0, 32, 32, // 10.png
    32, 0, 32, 32, // 11.png
    0, 0, 32, 32, // 12.png
};