// Autogenerated file

#ifndef CSSMUGS_H__
#define CSSMUGS_H__

#include <stdint.h>

#define CSSMUGS_BITMAP_WIDTH   128
#define CSSMUGS_BITMAP_HEIGHT  128
#define CSSMUGS_NUM_IMAGES     12

#define CSSMUGS_01_png 0
#define CSSMUGS_02_png 1
#define CSSMUGS_03_png 2
#define CSSMUGS_04_png 3
#define CSSMUGS_05_png 4
#define CSSMUGS_06_png 5
#define CSSMUGS_07_png 6
#define CSSMUGS_08_png 7
#define CSSMUGS_09_png 8
#define CSSMUGS_10_png 9
#define CSSMUGS_11_png 10
#define CSSMUGS_12_png 11

extern const uint16_t CSSMUGS_texcoords[];

#endif // CSSMUGS_H__
