// Autogenerated file

#ifndef HAND_H__
#define HAND_H__

#include <stdint.h>

#define HAND_BITMAP_WIDTH   32
#define HAND_BITMAP_HEIGHT  32
#define HAND_NUM_IMAGES     1

#define HAND_01_png 0

extern const uint16_t HAND_texcoords[];

#endif // HAND_H__
