// Autogenerated file

#ifndef LOCKED_H__
#define LOCKED_H__

#include <stdint.h>

#define LOCKED_BITMAP_WIDTH   128
#define LOCKED_BITMAP_HEIGHT  128
#define LOCKED_NUM_IMAGES     1

#define LOCKED_locked_texture_png 0

extern const uint16_t LOCKED_texcoords[];

#endif // LOCKED_H__
