// Autogenerated file

#ifndef OPT_H__
#define OPT_H__

#include <stdint.h>

#define OPT_BITMAP_WIDTH   64
#define OPT_BITMAP_HEIGHT  64
#define OPT_NUM_IMAGES     1

#define OPT_opt_texture_png 0

extern const uint16_t OPT_texcoords[];

#endif // OPT_H__
