// Autogenerated file

#ifndef SOLO_H__
#define SOLO_H__

#include <stdint.h>

#define SOLO_BITMAP_WIDTH   128
#define SOLO_BITMAP_HEIGHT  128
#define SOLO_NUM_IMAGES     1

#define SOLO_solo_texture_png 0

extern const uint16_t SOLO_texcoords[];

#endif // SOLO_H__
