// Autogenerated file

#ifndef VAULT_H__
#define VAULT_H__

#include <stdint.h>

#define VAULT_BITMAP_WIDTH   128
#define VAULT_BITMAP_HEIGHT  128
#define VAULT_NUM_IMAGES     1

#define VAULT_vault_texture_png 0

extern const uint16_t VAULT_texcoords[];

#endif // VAULT_H__
