// Autogenerated file

#ifndef VS_H__
#define VS_H__

#include <stdint.h>

#define VS_BITMAP_WIDTH   128
#define VS_BITMAP_HEIGHT  128
#define VS_NUM_IMAGES     1

#define VS_vs_texture_png 0

extern const uint16_t VS_texcoords[];

#endif // VS_H__
