// Autogenerated file

#ifndef ATLAS_H__
#define ATLAS_H__

#include <stdint.h>

#define ATLAS_BITMAP_WIDTH   128
#define ATLAS_BITMAP_HEIGHT  256
#define ATLAS_NUM_IMAGES     16

#define ATLAS_01_png 0
#define ATLAS_02_png 1
#define ATLAS_03_png 2
#define ATLAS_04_png 3
#define ATLAS_05_png 4
#define ATLAS_06_png 5
#define ATLAS_07_png 6
#define ATLAS_08_png 7
#define ATLAS_09_png 8
#define ATLAS_10_png 9
#define ATLAS_11_png 10
#define ATLAS_12_png 11
#define ATLAS_13_png 12
#define ATLAS_14_png 13
#define ATLAS_15_png 14
#define ATLAS_16_png 15

extern const uint16_t ATLAS_texcoords[];

#endif // ATLAS_H__
